### ISSUE TITLE
Create Setting form rejecting all values for the 'Add/Remove delta' field.

### ISSUE THREAD

**Issue by agronaught** [doitintl/shamash#57]
## EXPECTED BEHAVIOR
Create setting form is rejecting all values for the 'Add/Remove' delta field.   I'll look at why tomorrow, but its preventing the service from working as it should.

![screenshot from 2018-03-28 17-56-07](https://user-images.githubusercontent.com/544882/38013574-56b4b814-32b1-11e8-9015-0d2134b83547.png)

**Comment by avivl** [comment]
@agronaught thank you for reporting this. I'll look at this later today
