### ISSUE TITLE
target number of nodes must be int

### ISSUE THREAD

**Issue by ktong** [doitintl/shamash#61]
/patch?cluster_name=shappy-dev&new_workers=2&new_preemptible=9.41868512111

## EXPECTED BEHAVIOR
the new_preemptible should be int like 9

## ACTUAL BEHAVIOR
get 9.41868512111

## STEPS TO REPRODUCE
* max nodes set to 100
* all others are edefault

**Comment by avivl** [comment]
@ktong do you have logs?
